# Site settings
title: "Park Research Page: Advanced Catalytic and Energy Materials"
email: philosspark@gmail.com
description: Academic webpage of Dr. Seyeon Park
baseurl: ""
url: "https://SeanPark05.github.io"

# Google analytics ID: Uncomment and your own, if you like
# google_analytics: XX
# google_analytics_4: XXX
# google_tag_manager: XXX

# Footer info
affiliation: >
    Sean Park, Ph.D.<br/>
    Postdoctoral researcher associate<br/>
    University of Pennsylvania

location: >
  University of Pennsylvania<br/>
  Department of Chemical and Biomolecular Engineering<br/>
  3340 Smith Walk Roy and Diana Vagelos Laboratories<br/>
  Philadelphia, PA 19104

contact: >
    <a href="mailto:philosspark@gmail.com" target="_blank"><i class="fa fa-envelope fa-1x"></i> Contact</a> <br/>
    <a href="https://github.com/sbryngelson/academic-website-template"><i class="fa fa-github fa-1x"></i> Site template</a>

# Pages shown in navbar
nav_pages:
  - name: about
  - name: research
  - name: publication
  - name: teaching
  - name: news
  - name: gallery

include:
  - .htaccess
  - _pages

# Conversion
markdown: kramdown
highlighter: rouge
lsi: false
excerpt_separator: "\n\n"
incremental: false

# Markdown Processing
kramdown:
  input: GFM
  hard_wrap: false
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  smart_quotes: lsquo,rsquo,ldquo,rdquo
  enable_coderay: false
  parse_block_html: true # default for kramdown is false. This will enable using Markdown links


plugins: ['jekyll/scholar']

scholar:

  last_name: Doe
  first_name: [John]

  style: citesty
  locale: en

  source: /assets/
  bibliography: ref.bib
  bibliography_template: bibtemplate
  sort_by: year, month
  order: descending

  replace_strings: true
  join_strings: true

  details_dir: bibliography
  details_layout: bibtex.html
  details_link: Details

  query: "@*"

  bibliography_list_attributes:
    reversed: "reversed"

exclude:
  - Gemfile
  - Gemfile.lock
  - update_boostrap.sh
  - switch_theme.sh
  - tags
  - Rakefile
